/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.tomasz.stepien.wlasnyprojekt;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author tomme
 */
public class WlasnyProjekt extends javax.swing.JFrame {
    /**
     * Creates new form WlasnyProjekt
     */
    public WlasnyProjekt() {
        initComponents();
        ts_jLabelLogo.setIcon(new ImageIcon(absolutePathToResource+"logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ts_jPanelMain = new javax.swing.JPanel();
        ts_jProgressBar = new javax.swing.JProgressBar();
        ts_jLabelLogo = new javax.swing.JLabel();
        ts_jLabelNazwa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ts_jComboBox = new javax.swing.JComboBox<>();
        ts_jLabelImage = new javax.swing.JLabel();
        ts_jMenuBar1 = new javax.swing.JMenuBar();
        ts_jMenuPlik = new javax.swing.JMenu();
        ts_jMenuItemZapisz = new javax.swing.JMenuItem();
        ts_jMenuItemWczytaj = new javax.swing.JMenuItem();
        ts_jMenuItemZamknij = new javax.swing.JMenuItem();
        ts_jMenuEdycja = new javax.swing.JMenu();
        ts_jMenu11 = new javax.swing.JMenu();
        ts_jMenuItemGreen = new javax.swing.JMenuItem();
        ts_jMenuItemYellow = new javax.swing.JMenuItem();
        ts_jMenu19 = new javax.swing.JMenu();
        ts_jMenuItemZwykla = new javax.swing.JMenuItem();
        ts_jMenuItemInna = new javax.swing.JMenuItem();
        ts_jMenuO = new javax.swing.JMenu();
        ts_jMenuItemO = new javax.swing.JMenuItem();
        ts_jMenuHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wybor obrazkow");
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        ts_jLabelNazwa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ts_jLabelNazwa.setText("Wybierz sobie zwierzątko");

        ts_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Big Floppa", "Troll Floppa", "Sogga", "Mad Drip Floppa" }));
        ts_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ts_jPanelMainLayout = new javax.swing.GroupLayout(ts_jPanelMain);
        ts_jPanelMain.setLayout(ts_jPanelMainLayout);
        ts_jPanelMainLayout.setHorizontalGroup(
            ts_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ts_jPanelMainLayout.createSequentialGroup()
                .addComponent(ts_jLabelNazwa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ts_jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(ts_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ts_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ts_jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ts_jPanelMainLayout.createSequentialGroup()
                        .addComponent(ts_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(ts_jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ts_jPanelMainLayout.setVerticalGroup(
            ts_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ts_jPanelMainLayout.createSequentialGroup()
                .addGroup(ts_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ts_jLabelNazwa, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(ts_jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ts_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ts_jComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(ts_jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 31, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        ts_jMenuPlik.setText("Plik");

        ts_jMenuItemZapisz.setText("Zapisz");
        ts_jMenuItemZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemZapiszActionPerformed(evt);
            }
        });
        ts_jMenuPlik.add(ts_jMenuItemZapisz);

        ts_jMenuItemWczytaj.setText("Wczytaj");
        ts_jMenuItemWczytaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemWczytajActionPerformed(evt);
            }
        });
        ts_jMenuPlik.add(ts_jMenuItemWczytaj);

        ts_jMenuItemZamknij.setText("Zamknij");
        ts_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemZamknijActionPerformed(evt);
            }
        });
        ts_jMenuPlik.add(ts_jMenuItemZamknij);

        ts_jMenuBar1.add(ts_jMenuPlik);

        ts_jMenuEdycja.setText("Edycja");

        ts_jMenu11.setText("Zmień tło");

        ts_jMenuItemGreen.setText("Zielone");
        ts_jMenuItemGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemGreenActionPerformed(evt);
            }
        });
        ts_jMenu11.add(ts_jMenuItemGreen);

        ts_jMenuItemYellow.setText("Żółte");
        ts_jMenuItemYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemYellowActionPerformed(evt);
            }
        });
        ts_jMenu11.add(ts_jMenuItemYellow);

        ts_jMenuEdycja.add(ts_jMenu11);

        ts_jMenu19.setText("Zmień czcionke");

        ts_jMenuItemZwykla.setText("Zwykła");
        ts_jMenuItemZwykla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemZwyklaActionPerformed(evt);
            }
        });
        ts_jMenu19.add(ts_jMenuItemZwykla);

        ts_jMenuItemInna.setText("Inna");
        ts_jMenuItemInna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemInnaActionPerformed(evt);
            }
        });
        ts_jMenu19.add(ts_jMenuItemInna);

        ts_jMenuEdycja.add(ts_jMenu19);

        ts_jMenuBar1.add(ts_jMenuEdycja);

        ts_jMenuO.setText("O programie");

        ts_jMenuItemO.setText("O programie");
        ts_jMenuItemO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemOActionPerformed(evt);
            }
        });
        ts_jMenuO.add(ts_jMenuItemO);

        ts_jMenuHelp.setText("Pomoc");
        ts_jMenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuHelpActionPerformed(evt);
            }
        });
        ts_jMenuO.add(ts_jMenuHelp);

        ts_jMenuBar1.add(ts_jMenuO);

        setJMenuBar(ts_jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ts_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jComboBoxActionPerformed
        changeImage();
    }//GEN-LAST:event_ts_jComboBoxActionPerformed

    private void ts_jMenuItemZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemZapiszActionPerformed
        saveConfig();
    }//GEN-LAST:event_ts_jMenuItemZapiszActionPerformed

    private void ts_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ts_jMenuItemZamknijActionPerformed

    private void ts_jMenuItemGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemGreenActionPerformed
        ts_jPanelMain.setBackground(Color.green);
    }//GEN-LAST:event_ts_jMenuItemGreenActionPerformed

    private void ts_jMenuItemYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemYellowActionPerformed
        ts_jPanelMain.setBackground(Color.yellow);
    }//GEN-LAST:event_ts_jMenuItemYellowActionPerformed

    private void ts_jMenuItemInnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemInnaActionPerformed
        ts_jLabelNazwa.setFont(new Font("Tempus Sans ITC", Font.PLAIN, 24));
    }//GEN-LAST:event_ts_jMenuItemInnaActionPerformed

    private void ts_jMenuItemZwyklaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemZwyklaActionPerformed
        ts_jLabelNazwa.setFont(new Font("Tahoma", Font.PLAIN, 24));
    }//GEN-LAST:event_ts_jMenuItemZwyklaActionPerformed

    private void ts_jMenuItemOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemOActionPerformed
        JOptionPane.showMessageDialog(this,"Wykonał: Tomasz Stępień");
    }//GEN-LAST:event_ts_jMenuItemOActionPerformed

    private void ts_jMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuHelpActionPerformed
        JOptionPane.showMessageDialog(this,"Brak");
    }//GEN-LAST:event_ts_jMenuHelpActionPerformed

    private void ts_jMenuItemWczytajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemWczytajActionPerformed
        loadConfig();
    }//GEN-LAST:event_ts_jMenuItemWczytajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WlasnyProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WlasnyProjekt().setVisible(true);
            }
        });
    }
    private void progressBar(){
        ts_jProgressBar.setValue(0);
        try{
            Thread.sleep(3);
        }catch(Exception e){
        }
        for(int i=0;i<101;i++){
            try{
                Thread.sleep(3);
            }catch(Exception e){
            }
            ts_jProgressBar.setValue(i);
        }
    }
    private void changeImage(){
        String img = (String) ts_jComboBox.getSelectedItem();
        switch(img){
            case "Big Floppa":
                progressBar();
                ts_jLabelImage.setIcon(new ImageIcon(absolutePathToResource+"floppa.png"));
                break;
            case "Troll Floppa":
                progressBar();
                ts_jLabelImage.setIcon(new ImageIcon(absolutePathToResource+"troll.png"));
                break;
            case "Sogga":
                progressBar();
                ts_jLabelImage.setIcon(new ImageIcon(absolutePathToResource+"sogga.png"));
                break;
            case "Mad Drip Floppa":
                progressBar();
                ts_jLabelImage.setIcon(new ImageIcon(absolutePathToResource+"maddrip.png"));
                break;
            default:
                break;
        }
        System.out.println(img);
        
    }
    private void saveConfig(){
        try{
            File f = new File("config.txt");
            FileWriter fw = new FileWriter(f);
            String img = (String) ts_jComboBox.getSelectedItem();
            fw.write(img+";");
            fw.close();
        }catch(IOException e){
            System.out.println("ERROR: "+e.toString());
	}
    }
    private void loadConfig(){
        JFileChooser jFileChooser = new JFileChooser();
        try{
            File f = new File("config.txt");
            Scanner sc = new Scanner(f);
            String [] img = new String[1];
            img = sc.nextLine().split(";");
            //Plec
            switch(img[0]){
            case "Big Floppa":
                progressBar();
                ts_jLabelImage.setIcon(new ImageIcon(absolutePathToResource+"floppa.png"));
                break;
            case "Troll Floppa":
                progressBar();
                ts_jLabelImage.setIcon(new ImageIcon(absolutePathToResource+"troll.png"));
                break;
            case "Sogga":
                progressBar();
                ts_jLabelImage.setIcon(new ImageIcon(absolutePathToResource+"sogga.png"));
                break;
            case "Mad Drip Floppa":
                progressBar();
                ts_jLabelImage.setIcon(new ImageIcon(absolutePathToResource+"maddrip.png"));
                break;
            default:
                break;
        }
            
        }catch(FileNotFoundException ex){
            System.out.print(ex.toString());
        }
    }
    
    String absolutePathToResource = "src\\main\\java\\resources\\";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> ts_jComboBox;
    private javax.swing.JLabel ts_jLabelImage;
    private javax.swing.JLabel ts_jLabelLogo;
    private javax.swing.JLabel ts_jLabelNazwa;
    private javax.swing.JMenu ts_jMenu11;
    private javax.swing.JMenu ts_jMenu19;
    private javax.swing.JMenuBar ts_jMenuBar1;
    private javax.swing.JMenu ts_jMenuEdycja;
    private javax.swing.JMenuItem ts_jMenuHelp;
    private javax.swing.JMenuItem ts_jMenuItemGreen;
    private javax.swing.JMenuItem ts_jMenuItemInna;
    private javax.swing.JMenuItem ts_jMenuItemO;
    private javax.swing.JMenuItem ts_jMenuItemWczytaj;
    private javax.swing.JMenuItem ts_jMenuItemYellow;
    private javax.swing.JMenuItem ts_jMenuItemZamknij;
    private javax.swing.JMenuItem ts_jMenuItemZapisz;
    private javax.swing.JMenuItem ts_jMenuItemZwykla;
    private javax.swing.JMenu ts_jMenuO;
    private javax.swing.JMenu ts_jMenuPlik;
    private javax.swing.JPanel ts_jPanelMain;
    public static javax.swing.JProgressBar ts_jProgressBar;
    // End of variables declaration//GEN-END:variables
}
